export const exam20210613_section2 = {
  currentLyrics: [
    4045, 6080, 13067, 15039, 17025, 22010, 33073, 32049, 36000, 37089, 45057, 50038, 53069, 57029, 61002, 67012, 73010, 75052, 80044, 84079, 91022,
    94020, 98004, 102031, 127035, 147052, 166099,
  ],

  englishArr: [
    "W: I'm thinking of buying a car.",
    "I wouldn't need to use it every day,  but I think it would be very convenient to have one for the weekends.",
    "M: That's exciting.",
    'Would this be your first car?',
    'W: No.I actually owned a car for a little while when I lived in Miami.',
    "You see in America, many cities don't have good public transport, so most people need their own car to get around.",
    'M: I see.',
    'So have you got your mind set on a specific model?',
    'W: No, not really.',
    "I've heard that German cars are very reliable, but I haven't decided on a specific model yet.",
    "I'd also like it to be small, so that it's easy to drive in the city.",
    'M: I have a friend who sells second-hand cars.',
    'In fact, I think his family owns the business.',
    "He's a really nice guy, and he knows a lot about cars.",
    'I could give you his phone number if you want, and  you could call him and ask him questions.',
    "W: Hmm, that's nice of you, but I don't want to feel obliged to buy one of his cars.",
    "M: Oh no, he's not like that.",
    "He's a good friend of mine,  and he would never try to pressure you or cheat you.",
    'W: Well, if you trust him, then, I guess it should be okay.',
    'To be honest, I could use some help in deciding what type of vehicle would best suit my needs.',
    'Speaking to an expert would be a good idea.',
    'M: Exactly.You have nothing to worry about.',
    "He's a lovely guy, and he'll be happy to help.",
    'Question 12. Why does the woman want to have a car?',
    'Question 13. What does the woman say about German cars?',
    'Question 14. What does the man recommend the woman do?',
    "Question 15. What do we learn about the man's friend from the conversation?",
  ],

  chineseArr: [
    '女：我正在考虑买辆车。',
    '虽然我不会每天都用，但我想周末有辆车会很方便。',
    '男： 这令人激动。',
    '这是你的第一辆车吗？',
    '女：不，事实上，我在迈阿密居住时，有一段时间是有车的。',
    '你看，在美国，许多城市都没有良好的公共交通，所以大多数人需要自己开车出行。',
    '男： 我明白了。',
    '那你想好要买哪种具体的车型了吗？',
    '女：没，还没呢。',
    '我听说德国车很可靠。但是我还没有决定具体的车型。',
    '我还希望车小一点，这样在城市里开车就容易了。',
    '男： 我有个卖二手车的朋友。',
    '事实上，我感觉他家开了个二手车店。',
    '他人非常好，对汽车很了解。',
    '如果你需要的话，我可以把他的电话号码给你。你可以打电话给他，向他咨询一些问题。',
    '女：嗯，你真好，但是我不想觉得要被迫去买辆他的车。',
    '男： 噢，不，他不是那样的人。',
    '他是我的一个好朋友。他不会给你施加压力或者欺骗你。',
    '女：嗯，如果你信任他，那我想应该没问题。',
    '老实说，我可能需要一些帮助来决定什么样的车最适合我。',
    '和专业人士聊聊会是个好主意。',
    '男： 的确，你没什么可担心的。',
    '他人不错，会很乐意帮忙的。',
    '问题12：女士为什么想要一辆车？',
    '问题13：关于德国车，女士说了什么？',
    '问题14：男士建议女士做什么？',
    '问题15：关于男士的朋友，我们可以从对话中了解到什么？',
  ],

  englishClueArr: [
    "W: I'm thinking of buying a car. I wouldn't need to use it every day, (12) but I think it would be very convenient to have one for the weekends.",
    "M: That's exciting. Would this be your first car?",
    "W: No. I actually owned a car for a little while when I lived in Miami. You see in America, many cities don't have good public transport, so most people need their own car to get around.",
    'M: I see. So have you got your mind set on a specific model?',
    "W: No, not really. (13)<u> I've heard that German cars are very reliable, </u>but I haven't decided on a specific model yet. I'd also like it to be small, so that it's easy to drive in the city.",
    "M: I have a friend who sells second-hand cars. In fact, I think his family owns the business. He's a really nice guy, and he knows a lot about cars. I could give you his phone number if you want, and (14)<u> you could call him and ask him questions.</u>",
    "W: Hmm, that's nice of you, but I don't want to feel obliged to buy one of his cars.",
    "M: Oh no, he's not like that.  He's a good friend of mine, (15) <u>and he would never try to pressure you or cheat you.</u>",
    'W: <u>Well, if you trust him, then, I guess it should be okay. </u>To be honest, I could use some help in deciding what type of vehicle would best suit my needs. Speaking to an expert would be a good idea.',
    "M: Exactly. You have nothing to worry about. He's a lovely guy, and he'll be happy to help.",
    'Questions 12 to 15 are based on the conversation you have just heard. ',
    'Question 12. Why does the woman want to have a car? ',
    'Question 13. What does the woman say about German cars? ',
    'Question 14. What does the man recommend the woman do? ',
    "Question 15. What do we learn about the man's friend from the conversation?",
  ],

  chineseClueArr: [
    '女：我正在考虑买辆车。虽然我不会每天都用，（12）<u>但我想周末有辆车会很方便。</u>',
    '男： 这令人激动。这是你的第一辆车吗？',
    '女：不，事实上，我在迈阿密居住时，有一段时间是有车的。你看，在美国，许多城市都没有良好的公共交通，所以大多数人需要自己开车出行。',
    '男： 我明白了。那你想好要买哪种具体的车型了吗？',
    '女：没，还没呢。（13）<u>我听说德国车很可靠。</u>但是我还没有决定具体的车型。我还希望车小一点，这样在城市里开车就容易了。',
    '男： 我有个卖二手车的朋友。事实上，我感觉他家开了个二手车店。他人非常好，对汽车很了解。如果你需要的话，我可以把他的电话号码给你。（14）<u>你可以打电话给他，向他咨询一些问题。</u>',
    '女：嗯，你真好，但是我不想觉得要被迫去买辆他的车。',
    '男： 噢，不，他不是那样的人。（15）<u>他是我的一个好朋友。他不会给你施加压力或者欺骗你。</u>',
    '女：<u>嗯，如果你信任他，那我想应该没问题。</u>老实说，我可能需要一些帮助来决定什么样的车最适合我。和专业人士聊聊会是个好主意。',
    '男： 的确，你没什么可担心的。他人不错，会很乐意帮忙的。',
    '问题12：女士为什么想要一辆车？',
    '问题13：关于德国车，女士说了什么？',
    '问题14：男士建议女士做什么？',
    '问题15：关于男士的朋友，我们可以从对话中了解到什么？',
  ],

  optionEnglish: [
    ['For commuting to work.', 'For long-distance travel.', 'For convenience at weekends.', 'For getting around in Miami.'],
    ['They are compact.', 'They are reliable. ', 'They are spacious. ', 'They are easy to drive.'],
    ['Buy a second-hand car. ', 'Trust her own judgment. ', 'Seek advice from his friend. ', 'Look around before deciding.'],
    ['He can be trusted. ', 'He sells new cars. ', 'He is starting a business. ', 'He is a successful car dealer.'],
  ],

  optionsChinese: [
    ['为了通勤上班。', '为了长途旅行。', '为了周末方便。', '为了在迈阿密四处走动。'],
    ['它们很紧凑。', '它们很可靠。', '它们很宽敞。', '它们易于驾驶。'],
    ['买辆二手车。', '相信她自己的判断。', '向他朋友寻求建议。', '看看再做决定。'],
    ['他是可信赖的。', '他售卖新车。', '他正在创业。', '他是一个成功的汽车经销商。'],
  ],

  questionIndex: [12, 13, 14, 15],
};

export const exam20210613_judement_result_section2 = {
  //文章简介,材料分析
  passage_abstract: '根据选项中的高频词car、For以及与车性能相关的单词或词组spacious、easy to drive等，可推断出，该材料可能围绕购车展开。',
  //这篇文章的重点单词
  important_words: [
    'convenient adj. 方便的；便利的',
    'actually adv. 事实上；实际上 ',
    'own v. 拥有 adj. 属于自己的',
    'transport n. 交通；运输',
    'specific adj. 具体的；特定的',
    'model n. 样式；模型 ',
    'reliable adj. 可靠的；可信赖的',
    'second-hand adj. 二手的；旧的 ',
    'obliged adj. 必须的；有责任的 ',
    'vehicle n. 车辆',
    'suit v. 适合 n. 套装',
    'expert n. 专家 adj. 熟练的',
  ],
  //错误选项 analysis题目解析 interference干扰项分析
  options: [
    {
      your_answer: 2,
      correct_answer: 2,
      analysis:
        'C选项对应音频内容but it would be very convenient to have one for the weekends，其中weekends在音频中原词复现，convenience则是音频中convenient的派生词同义替换，故为正确答案。',
      interference:
        'A、B选项音频均未提及，故均排除；D选项中的getting around in Miami是对音频中I actually owned ... lived in Miami和You see ... their own car to get around的杂糅，音频并未提及女士想有辆车是为了能在迈阿密四处走动，故排除。',
      tyzd: '音频对应句中，出现了表示转折的but，转折之后的内容往往会出考点，考生需要多加留意。',
    },
    {
      your_answer: 1,
      correct_answer: 1,
      analysis: 'B选项对应音频中的German cars are very reliable，选项中的They指代的正是German cars，故为正确答案。',
      interference:
        'A、C选项音频均未提及，故均排除；D选项中的easy to drive在音频中虽有提及，但这是女士希望车小一点的原因，并非女士对德国车的描述，故排除。',
      tyzd: '音频对应句中，German cars语速放缓且出现明显重读，其后可能会出现重要信息，考生需要格外留意。',
    },
    {
      your_answer: 2,
      correct_answer: 2,
      analysis: 'C选项是对音频内容you could call him and ask him questions的句义转述，给他打电话询问，换言之就是向他寻求建议，故为正确答案。',
      interference:
        "A选项是对音频中I'm thinking of buying a car和a friend who sells second-hand cars的杂糅，男士并未建议女士买辆二手车，只是建议女士去咨询下他的那位卖二手车的朋友，故排除；B选项音频未提及，故排除；D选项中的deciding为干扰字眼，音频并未提及男士建议女士看看再做决定，故排除。",
      tyzd: '音频对应句中，you could call him后面有明显的停顿，可能提示重要内容，考生可多加留意。',
    },
    {
      your_answer: 0,
      correct_answer: 0,
      analysis: 'D选项在音频内容... ask Paul to bring his computer and speakers中原词复现，故为正确答案。',
      interference:
        'B选项显然与音频内容a friend who sells second-hand cars相悖，故排除；C选项中的business为干扰字眼，音频中只提到他家owns the business，并未提及他starting a business，正创业，故排除；D选项音频未提及，故排除。',
      tyzd: '音频对应句中，if you trust him有重读，可能存在考点，考生需要多加注意。',
    },
  ],
};

export const exam20210613_section1 = {
  currentLyrics: [
    3001, 7000, 10019, 14090, 18040, 20071, 24078, 36053, 38090, 44037, 46079, 49081, 56030, 58070, 64028, 65050, 66068, 68067, 77006, 79036, 84071,
    87063, 89096, 113091, 137044, 157048,
  ],

  englishArr: [
    'M:  So what time do you think we should have the party on Saturday?',
    'W: How about inviting people to come at 6:00 p.m.?',
    "Then we'll have the afternoon to prepare food and drink, and stuff like that.",
    'M: Yes, I was thinking that around 6:00 would be good, too.',
    'What food should we provide?',
    'W: Well, I had thought about baking a cake and some biscuits.',
    'And now, I think we should prepare some sandwiches and snacks, and some other kinds of food, so that people can just help themselves, rather than getting everyone to sit down at the table to eat a meal.',
    "I think that's a bit too formal.",
    "It's better to let people walk around and talk to each other, or sit where they like.",
    'M: Yes, that sounds good.',
    "I'll go to the supermarket to get some drinks.",
    'I think I might try that big new supermarket on the other side of town and see what they have.',
    "I've not been there before.",
    'I think we should get some beer and wine, and some fruit juice and other soft drinks.',
    'What do you think?',
    'W: Sounds great!',
    'I think those drinks will be enough.',
    'And I heard that the new supermarket offers some big discounts to attract customers, so going there should be a great idea.',
    'What should we do about music?',
    'M:  Maybe we should ask Paul to bring his computer and speakers, so that we can play some music.',
    'He has a great collection of different stuff.',
    'W: Yes, all right.',
    'Question 8: What are the speakers mainly talking about?',
    'Question 9: Why does the woman say it is a good idea to serve foods that guests can help themselves to?',
    'Question 10: What does the woman say about the new supermarket?',
    'Question 11: What does the man suggest they ask Paul to do?',
  ],

  chineseArr: [
    '男：那你觉得我们周六什么时候开派对？',
    '女：邀请大家下午6点来怎么样？',
    '这样我们就有一下午的时间来准备食物和饮料之类的东西。',
    '男： 是的，我也觉得6点左右很好。',
    '我们应该提供什么食物？',
    '女：嗯，我考虑过烤蛋糕和饼干。',
    '现在我认为我们应该准备一些三明治、零食和其他种类的食物，这样大家就可以自取所需，不用让大家都坐在桌子旁吃饭。',
    '我觉得那有点太正式了。',
    '最好能让大家四处走动，互相交谈，或者坐在他们喜欢的地方。',
    '男： 是的，听起来不错。',
    '我要去超市买些饮料。',
    '我可能会去市里另一边那家新开的大超市看看那里有什么。',
    '我以前没去过那里。',
    '我想我们应该买些啤酒、葡萄酒、果汁和其他软饮。',
    '你觉得呢？',
    '女：听起来不错。',
    '我想这些饮料就够了。',
    '我听说那家新开的超市会提供一些很大的折扣来吸引顾客，所以去那里应该是个好主意。',
    '关于音乐，我们要做些什么准备呢？',
    '男： 也许我们应该让Paul带来他的电脑和音响，这样我们就可以播放音乐了。',
    '他收集了很多不同的音乐。',
    '女：是的，那就这样。',
    '问题8：讲话者主要在谈论什么？',
    '问题9：为什么女士说让客人可以自取食物是个好主意？',
    '问题10：关于新开的超市，女士说了什么？',
    '问题11：男士建议他们让Paul做什么？',
  ],

  englishClueArr: [
    'M: (8)<u> So what time do you think we should have the party on Saturday?</u>',
    "W: <u>How about inviting people to come at 6:00 p.m.? Then we'll have the afternoon to prepare food and drink, and stuff like that.</u>",
    'M: Yes, I was thinking that around 6:00 would be good, too. What food should we provide?',
    "W: Well, I had thought about baking a cake and some biscuits. And now, I think we should prepare some sandwiches and snacks, and some other kinds of food, so that people can just help themselves, rather than getting everyone to sit down at the table to eat a meal. I think that's a bit too formal. (9)<u> It's better to let people walk around and talk to each other, or sit where they like.</u>",
    "M: Yes, that sounds good. I'll go to the supermarket to get some drinks. I think I might try that big new supermarket on the other side of town and see what they have. I've not been there before. I think we should get some beer and wine, and some fruit juice and other soft drinks. What do you think?",
    'W: Sounds great! I think those drinks will be enough. (10)<u> And I heard that the new supermarket offers some big discounts to attract customers,</u> so going there should be a great idea. What should we do about music?',
    'M: (11) <u>Maybe we should ask Paul to bring his computer and speakers, so that we can play some music. </u>He has a great collection of different stuff.',
    'W: Yes, all right.',
    'Question 8. What are the speakers mainly talking about? ',
    'Question 9. Why does the woman say it is a good idea to serve foods that guests can help themselves to? ',
    'Question 10. What does the woman say about the new supermarket?',
    'Question 11. What does the man suggest they ask Paul to do? ',
  ],

  chineseClueArr: [
    '男：（8）<u>那你觉得我们周六什么时候开派对？</u>',
    '女：<u>邀请大家下午6点来怎么样？这样我们就有一下午的时间来准备食物和饮料之类的东西。</u>',
    '男： 是的，我也觉得6点左右很好。我们应该提供什么食物？',
    '女：嗯，我考虑过烤蛋糕和饼干。现在我认为我们应该准备一些三明治、零食和其他种类的食物，这样大家就可以自取所需，不用让大家都坐在桌子旁吃饭。我觉得那有点太正式了。（9）<u>最好能让大家四处走动，互相交谈，或者坐在他们喜欢的地方。</u>',
    '男： 是的，听起来不错。我要去超市买些饮料。我可能会去市里另一边那家新开的大超市看看那里有什么。我以前没去过那里。我想我们应该买些啤酒、葡萄酒、果汁和其他软饮。你觉得呢？',
    '女：听起来不错。我想这些饮料就够了。（10）<u>我听说那家新开的超市会提供一些很大的折扣来吸引顾客</u>，所以去那里应该是个好主意。关于音乐，我们要做些什么准备呢？',
    '男： （11）<u>也许我们应该让Paul带来他的电脑和音响，这样我们就可以播放音乐了。</u>他收集了很多不同的音乐。',
    '女：是的，那就这样。',
    '问题8：讲话者主要在谈论什么？',
    '问题9：为什么女士说让客人可以自取食物是个好主意？',
    '问题10：关于新开的超市，女士说了什么？',
    '问题11：男士建议他们让Paul做什么？',
  ],

  optionEnglish: [
    [
      "A surprise party for Paul's birthday. ",
      'Travel plans for the coming weekend. ',
      'The new market on the other side of town.  ',
      "Preparations for Saturday's get-together.",
    ],
    [
      'It enables guests to walk around and chat freely.  ',
      "It makes the hostess's job a whole lot easier. ",
      'It saves considerable time and labor. ',
      'It requires fewer tables and chairs.',
    ],
    [
      'It is quite close to her house. ',
      'It offers some big discounts. ',
      'It is more spacious and less crowded. ',
      'It sells local wines and soft drinks.',
    ],
    ['Cook a dish for the party. ', 'Arrive 10 minutes earlier. ', 'Prepare a few opening remarks. ', 'Bring his computer and speakers.'],
  ],

  optionsChinese: [
    ['为Paul生日举办的惊喜派对。', '下周末的旅行计划。', '城镇另一边的新市场。', '周六聚会的准备工作。'],
    ['这使得客人们可以自由走动和聊天。', '这使女主人的工作容易多了。', '这节省大量时间和劳动力。', '这需要的桌椅更少。'],
    ['它离她家很近。', '它提供了一些很大的折扣。', '它更宽敞，不那么拥挤。', '它售卖当地的葡萄酒和软饮。'],
    ['为聚会做一道菜。', '提前10分钟到达。', '准备一些开场白。', '带上他的电脑和音响。'],
  ],

  questionIndex: [8, 9, 10, 11],
};

export const exam20210613_judement_result_section1 = {
  //文章简介,材料分析
  passage_abstract: '根据选项中的高频词party以及与聚会相关的单词guests、hostess、dish等，可推断出，该材料可能围绕某次聚会展开。',
  //这篇文章的重点单词
  important_words: [
    'invite v. 邀请；招待',
    'prepare v. 准备；筹备',
    'stuff n. 材料；东西 v. 填塞；塞满',
    'provide v. 提供；规定',
    'bake v. 烘焙；烤 ',
    'snack n. 小吃；点心',
    'formal adj. 正式的；拘谨的',
    'offer v. 提供；主动提出 ',
    'discount n. 折扣 v. 对…打折',
    'attract v. 吸引',
    'speaker n. 扬声器；说话者',
    'collection n. 收集',
  ],
  //错误选项 analysis题目解析 interference干扰项分析
  tmp: [
    '音频开头部分就提出了问题，且后面的回答中包含具体的时间信息，问答之间往往会出考点，考生需格外注意。',
    '音频对应句中，let people walk around出现明显重读，可能提示重要内容，考生需要多加留意。',
    '音频对应句中，offers some big discounts存在较明显的重读，可能提示重要内容，考生需要格外注意。',
    '音频对应句前面出现了关于music的问句，问答之间往往会出考点，且Maybe we should ask Paul ...也有重读，考生需要多加注意。',
  ],
  options: [
    {
      your_answer: 3,
      correct_answer: 3,
      analysis:
        'D选项是对音频开头部分So what time do you think we should have the party on Saturday ... prepare food and drink的概括总结，其中Saturday在音频中原词复现，Preparations则是prepare的派生词同义替换，而get-together则同义替换party，故为正确答案。',
      interference:
        'A选项中的party、Paul’s均为干扰字眼，音频未提及其surprise和birthday，故排除；B选项音频未提及，故排除；C选项中的on the other side of town为干扰字眼，音频中说的是new supermarket，并非new market，故排除。',
      tyzd: '音频开头部分就提出了问题，且后面的回答中包含具体的时间信息，问答之间往往会出考点，考生需格外注意。',
    },
    {
      your_answer: 0,
      correct_answer: 0,
      analysis:
        "A选项对应音频内容It's better to let people walk around and talk to each other，其中walk around在音频中原词复现，chat同义替换talk，guests与people相对应，故为正确答案。",
      interference: 'B、C选项音频均未提及，故均排除；D选项中的tables为干扰字眼，音频并未提及requires fewer和chairs，故排除。',
      tyzd: '音频对应句中，let people walk around出现明显重读，可能提示重要内容，考生需要多加留意。',
    },
    {
      your_answer: 1,
      correct_answer: 1,
      analysis: 'B选项在音频内容And I heard that the new supermarket offers some big discounts to attract customers中原词复现，故为正确答案。',
      interference:
        'A、C选项音频均未提及，故均排除；D选项中的wines和soft drinks为干扰字眼，音频中只是男士提到，他们应该买一些葡萄酒和软饮，女士并没有提及这个新超市售卖地方葡萄酒和软饮，故排除。',
      tyzd: '音频对应句中，offers some big discounts存在较明显的重读，可能提示重要内容，考生需要格外注意。',
    },
    {
      your_answer: 3,
      correct_answer: 3,
      analysis: 'D选项在音频内容... ask Paul to bring his computer and speakers中原词复现，故为正确答案。',
      interference: 'A、B、C选项音频均未提及，故均排除。',
      tyzd: '音频对应句前面出现了关于music的问句，问答之间往往会出考点，且Maybe we should ask Paul ...也有重读，考生需要多加注意。',
    },
  ],
};

export const exam202206123_section2 = {
  currentLyrics: [
    2000, 5021, 9016, 10094, 14051, 19060, 28036, 31013, 39085, 42000, 48041, 58072, 60087, 63099, 72085, 80070, 87060, 94038, 108023, 114097, 120090,
    129011, 130081, 135052, 141078, 160054, 181005, 200096,
  ],

  englishArr: [
    'M: Hi, Jennifer.',
    'I’m really struggling with this semester’s workload.',
    'Do you have any advice?',
    'W:  Have you considered making a study guide?',
    'It’s a tool you can make yourself to take the stress out of studying.',
    'I’ve been using one since the start of last semester, and it has really helped relieve a lot of study pressure.',
    'M: Sounds like just what I need.',
    'My main problem is that my study folder is full of notes and worksheets, and is badly disorganized.',
    'I don’t know where to start.',
    'W: Okay.Well, the main thing is to have everything in the right place.',
    'Whatever you’re reviewing, it’s important that it’s arranged for your particular needs of that subject, and in the most user-friendly way you can.',
    'What kind of learner are you?',
    'M: Um, I’m not sure.',
    'W: Well, visual learners prefer using images, pictures, colors and maps to organize information.',
    'Logical learners have a linear mind and would rather use logic, reasoning and systems.',
    'I’m an emotional learner, which means I need to connect to information emotionally to understand it.',
    'M: Oh!I’m very much dependent on vision as a way of taking in information.',
    'W:  Well, I suggest reorganizing your notes using color-coded sections in your study guides, or using idea mapping to lay out the information and make it more quickly accessible.',
    'M: So you think I should arrange my notes using color and pictures in place of text.',
    'W: Yes, you’ll probably start to grasp information a lot quicker that way.',
    'As an emotional learner, I organize my notes into a story that I can connect to and recite to myself.',
    'M: That’s amazing.',
    'I didn’t know there were so many different ways to learn.',
    'Questions 12 to 15 are based on the conversation you have just heard.',
    'Question 12 What does the woman advise the man do?',
    'Question 13 What is the biggest problem the man has with his studies?',
    'Question 14 What kind of learner does the woman say she is?',
    'Question 15 What does the woman think the man can do with his notes?',
  ],

  chineseArr: [
    'M：你好，詹妮弗。',
    '这学期的课业负担让我很头疼。',
    '你有什么建议吗？',
    'W：你考虑过制作一个学习指南吗？',
    '这是一个你可以让自己减轻学习压力的工具。',
    '我从上学期开始就一直使用它，它确实帮助我缓解了很多学习压力。',
    'M：听起来正是我所需要的。',
    '我的主要问题是我的学习文件夹里装满了笔记和工作表，而且非常混乱。',
    '我不知道该从哪里开始。',
    'W：好的。嗯，最重要的是把所有的东西都放在正确的地方。',
    '无论你在复习什么，重要的是要根据你对这门学科的特定需求，以最方便使用的方式进行整理。',
    '你是什么样的学习者？',
    'M：嗯，我不确定。',
    'W：视觉型学习者更倾向于使用图像、图片、颜色和导图来组织信息。',
    '逻辑学习者是线性思维，他们更愿意使用逻辑、推理和系统（性地学习）。',
    '我是一个情感型学习者，这意味着我需要从情感上与信息联系起来才能理解它。',
    'M：哦！我非常依赖将视觉作为一种获取信息的方式。',
    'W：嗯，我建议在你的学习指南中使用颜色编码来重新组织你的笔记，或者使用思维导图来布局信息，使其更容易被理解。',
    'M：所以你认为我应该用颜色和图片代替文字来整理我的笔记。',
    'W：是的，这样你可能会开始更快地掌握信息。',
    '作为一个情感型学习者，我把我的笔记整理成一个故事，这样我就可以把它联系起来并背诵给自己听。',
    'M：太棒了。',
    '我不知道原来有那么多不同的学习方式。',
    '第 12 至 15 题是根据您刚才听到的对话提出的。',
    '问题12：女士建议男士做什么?',
    '问题13：男士在学习中最大的问题是什么？',
    '问题14：女士说她是一个什么样的学习者？',
    '问题15：女士认为男士可以怎样做笔记？',
  ],

  englishClueArr: [
    'M: Hi, Jennifer. I’m really struggling with this semester’s workload. Do you have any advice?',
    'W: (12) <u>Have you considered making a study guide</u>? It’s a tool you can make yourself to take the stress out of studying. I’ve been using one since the start of last semester, and it has really helped relieve a lot of study pressure.',
    'M: Sounds like just what I need. (13) <u>My main problem is that my study folder is full of notes and worksheets, and is badly disorganized.</u> I don’t know where to start.',
    'W: Okay. Well, the main thing is to have everything in the right place. Whatever you’re reviewing, it’s important that it’s arranged for your particular needs of that subject, and in the most user-friendly way you can. What kind of learner are you?',
    'M: Um, I’m not sure.',
    'W: Well, visual learners prefer using images, pictures, colors and maps to organize information. Logical learners have a linear mind and would rather use logic, reasoning and systems. (14) <u>I’m an emotional learner, which means I need to connect to information emotionally to understand it.</u>',
    'M: Oh! I’m very much dependent on vision as a way of taking in information.',
    'W: (15) <u>Well, I suggest reorganizing your notes using color-coded sections in your study guides, or using idea mapping to lay out the information and make it more quickly accessible.</u>',
    'M: <u>So you think I should arrange my notes using color and pictures in place of text.</u>',
    'W: <u>Yes,</u> you’ll probably start to grasp information a lot quicker that way. As an emotional learner, I organize my notes into a story that I can connect to and recite to myself.',
    'M: That’s amazing. I didn’t know there were so many different ways to learn.',
    'Questions 12 to 15 are based on the conversation you have just heard.',
    'Question 12 What does the woman advise the man do?',
    'Question 13 What is the biggest problem the man has with his studies?',
    'Question 14 What kind of learner does the woman say she is?',
    'Question 15 What does the woman think the man can do with his notes?',
  ],

  chineseClueArr: [
    'M：你好，詹妮弗。这学期的课业负担让我很头疼。你有什么建议吗？',
    'W：（12）<u>你考虑过制作一个学习指南吗？这是一个你可以让自己减轻学习压力的工具。我从上学期开始就一直使用它，它确实帮助我缓解了很多学习压力。</u>',
    'M：听起来正是我所需要的。（13）<u>我的主要问题是我的学习文件夹里装满了笔记和工作表，而且非常混乱。</u>我不知道该从哪里开始。',
    'W：好的。嗯，最重要的是把所有的东西都放在正确的地方。无论你在复习什么，重要的是要根据你对这门学科的特定需求，以最方便使用的方式进行整理。你是什么样的学习者？',
    'M：嗯，我不确定。',
    'W：视觉型学习者更倾向于使用图像、图片、颜色和导图来组织信息。逻辑学习者是线性思维，他们更愿意使用逻辑、推理和系统（性地学习）。（14）<u>我是一个情感型学习者，这意味着我需要从情感上与信息联系起来才能理解它。</u>',
    'M：哦！我非常依赖将视觉作为一种获取信息的方式。',
    'W：（15）<u>嗯，我建议在你的学习指南中使用颜色编码来重新组织你的笔记，或者使用思维导图来布局信息，使其更容易被理解。</u>',
    'M：所以你认为我应该用颜色和图片代替文字来整理我的笔记。',
    'W：是的，这样你可能会开始更快地掌握信息。作为一个情感型学习者，我把我的笔记整理成一个故事，这样我就可以把它联系起来并背诵给自己听。',
    'M：太棒了。我不知道原来有那么多不同的学习方式。',
    '问题12：女士建议男士做什么?',
    '问题13：男士在学习中最大的问题是什么？',
    '问题14：女士说她是一个什么样的学习者？',
    '问题15：女士认为男士可以怎样做笔记？',
  ],

  optionEnglish: [
    ['Prepare a study guide.', 'Consult his advisors.', 'Go over his notes regularly.', 'Take stress-relief sessions.'],
    [
      'His worksheets are terribly messy.',
      'He finds the workload too heavy.',
      'His study folder is badly disorganized.',
      'He has difficulty taking notes quickly.',
    ],
    ['A visual learner.', 'An emotional learner.', 'An organized learner.', 'A logical learner.'],
    [
      'Arrange them using color and pictures.',
      'Restructure them in a logical way.',
      'Commit them to memory after class.',
      'Organize them into a well-connected story.',
    ],
  ],

  optionsChinese: [
    ['准备一份学习指南。', '咨询他的指导老师。', '定期复习他的笔记。', '参加减压课程。'],
    ['他的活页练习题非常凌乱。', '他觉得工作量太繁重。', '他的学习文件夹非常混乱。', '他难以快速记笔记。'],
    ['视觉学习者。', '情感学习者。', '有条理的学习者。', '逻辑学习者。'],
    ['使用色彩和图画整理它们。', '以逻辑的方式重组它们。', '下课后牢记它们。', '将它们整理成一个联系紧密的故事。'],
  ],

  questionIndex: [12, 13, 14, 15],
};

export const exam202206123_judement_result_section2 = {
  //文章简介,材料分析
  passage_abstract:
    '根据选项中出现的高频词learner以及与学习相关的study guide、notes、class等词可推断出，本篇材料可能围绕学习相关的事情展开，涉及一些学习建议。',
  //这篇文章的重点单词
  important_words: [
    'struggle v. 在困境中挣扎；努力',
    'workload n. 工作量；工作负荷',
    'relieve v. 缓解；减轻',
    'folder n. 文件夹；纸夹',
    'disorganized adj. 杂乱无章的',
    'particular adj. 特定的',
    'be dependent on 依赖；依靠',
    'accessible adj．易懂的',
    'in place of 代替',
    'grasp v. 理解；领会',
  ],
  //错误选项 analysis题目解析 interference干扰项分析
  tmp: [
    'B选项音频未提及，故排除；C选项中的notes为干扰信息，音频并未提及要定期复习笔记，故排除；D选项中的stress-relief为干扰信息，音频并未提及减压相关的课程，故排除。',
    'A选项中的terribly messy在音频中未提及，故排除；B选项音频虽有提及，但并非题目所问的男士在学习中最大的问题，故排除；D选项中的notes为干扰信息，音频并未提及这位男士难以快速记笔记，故排除。',
    'A、D选项音频虽均有提及，但并非题目所问的女士所属的学习者类型，故排除；C选项为音频中badly organized和learner的杂糅，音频未提及这类学习者，故排除。',
    'B选项虽可对应音频中logical learner的学习方式，但与题目所问不符，故排除；C选项音频未提及，故排除；D选项音频虽有提及，但这是这位女士自己作为情感学习者的记笔记方式，与题目所问不符，故排除。',
  ],
  options: [
    {
      your_answer: 0,
      correct_answer: 0,
      analysis:
        'A选项与音频内容Have you considered making a study guide相对应，其中选项中的a study guide在音频中原词复现，Prepare则与make同义替换，故为正确答案。',
      interference:
        'B选项音频未提及，故排除；C选项中的notes为干扰信息，音频并未提及要定期复习笔记，故排除；D选项中的stress-relief为干扰信息，音频并未提及减压相关的课程，故排除。',
      tyzd: '音频对应处前面男士询问女士是否可以给一些建议，问答之间易出考点，考生需留意接下来的回答。',
    },
    {
      your_answer: 2,
      correct_answer: 2,
      analysis: 'C选项与音频内容My main problem is that my study folder ... is badly disorganized视听一致，故为正确答案。',
      interference:
        'A选项中的terribly messy在音频中未提及，故排除；B选项音频虽有提及，但并非题目所问的男士在学习中最大的问题，故排除；D选项中的notes为干扰信息，音频并未提及这位男士难以快速记笔记，故排除。',
      tyzd: '音频对应处出现了main problem is..这样的表达，通常在音频中如果出现main、most或者比较级的表达的话，极易出现考点，考生需留意。',
    },
    {
      your_answer: 1,
      correct_answer: 1,
      analysis: 'B选项在音频内容 I’m an emotional learner中原词复现，故为正确答案。',
      interference:
        'A、D选项音频虽均有提及，但并非题目所问的女士所属的学习者类型，故排除；C选项为音频中badly organized和learner的杂糅，音频未提及这类学习者，故排除。',
      tyzd: null,
    },
    {
      your_answer: 0,
      correct_answer: 0,
      analysis: 'A选项与音频内容you think I should arrange my notes using color and pictures ... Yes基本视听一致，故为正确答案。',
      interference:
        'B选项虽可对应音频中logical learner的学习方式，但与题目所问不符，故排除；C选项音频未提及，故排除；D选项音频虽有提及，但这是这位女士自己作为情感学习者的记笔记方式，与题目所问不符，故排除。',
      tyzd: '音频对应处出现了表示建议的表达I suggest，之后常常会出现考点，考生需留意。',
    },
  ],
};

export const before_submit = {
  currentLyrics: [
    3130, 7070, 9500, 11530, 14110, 16390, 19650, 25780, 29340, 31750, 34240, 35790, 37170, 38970, 42330, 46920, 49350, 54930, 56890, 58250, 60790,
    69720, 72710, 75190, 80600, 89840, 91050, 93930, 98320, 100780, 112440, 132620, 153910, 176160, 180970,
  ],
  englishArr: [
    'M: So, Lyndsay, do you like to text message on your cell phone?',
    'W: Yeah, I text message a lot.',
    'M: I don’t do it so much.',
    'I prefer to make a call if I’m in a hurry.',
    'W: Yeah, I go both ways.',
    'Sometimes I don ’t really want to talk to the person.',
    'I just want to ask them one question, so it’s much easier for me just to text message.',
    'If I call them，I’ll have to have a long conversation.',
    'M: Yeah, I can see what you mean.',
    'But I get off the phone pretty quickly when I call.',
    'I ’m not a big talker.',
    "W: Yeah, that's true.",
    'You don’t talk a lot.',
    'M: So are you fast at writing the messages with your thumb?',
    'W: Well, when I first got a cell phone, I was so slow.',
    'I thought I would never text message.',
    'But then people kept text-messaging me, so I felt obliged to learn how to text message.',
    'So now I’m pretty fast.',
    'What about you?',
    'M: Actually I have the opposite problem.',
    'When I first got my cell phone, I thought it was so cool to text message all my friends who have one, and I was pretty fast with my thumb then.',
    "But it seems like now I don't use it so much.",
    'I’ve got slower actually.',
    'W: Yeah, I think text messaging actually sort of has to do with your age.',
    'For example, people in high school, they text message a lot.',
    'But I asked my father if he texted messages, and guess what he said?',
    'M: What?',
    "W: He said he'd never text message.",
    'He thinks it’s very childish and unprofessional to text message.',
    'M: Yeah, I can see what he means.',
    'It’s considered pretty informal to text message to someone.',
    '8.What does the man say about himself?',
    '9.What does the woman tend to do while she is on the phone?',
    '10.Why did the man text message all his friends when he first got his cell phone?',
    '11.What does the woman’s father think of text messaging?',
  ],

  chineseArr: [
    '男：林赛，你喜欢在手机上发短信吗？',
    '女：是的，我经常发短信。',
    '男：我不经常这么做。',
    '如果我赶时间，我更愿意打个电话。',
    '女：是的，我是两者都使用的。',
    '有时我真的不想和那个人说话。',
    '我只是想问他们一个问题，所以对我而言，给他们发个短信就简单多了。',
    '如果我给他们打电话的话，就不得不长时间的谈话。',
    '男：是的，我能明白你的意思。',
    '但是当我打电话时，我很快就会挂电话。',
    '我不是个爱说大话的人。',
    '女：是的，这倒是真的。',
    '你话不多。',
    '男：你写信息的时候拇指打字速度很快吗？',
    '女：当我第一次拿手机发信息的时候，我很慢。',
    '我以为我永远不会发短信。',
    '但是当人们不停地给我发短信时，我觉得自己有必要学习如何发短信。',
    '所以现在我很快。',
    '那你呢？',
    '男：其实我和你恰恰相反。',
    '当我拥有第一部手机的时候，我觉得给所有拥有手机的朋友发短信是一件超酷的事情，那时我拇指打字速度很快。',
    '但现在看来，我并不怎么用它了。',
    '实际上我变慢了。',
    '女：是的，我认为短信实际上与你的年龄有关。',
    '例如，在高中的时候，人们经常发短信。',
    '但我问我父亲他是否发短信，猜猜他说什么？',
    '男：什么？',
    '女：他说他绝不会发短信。',
    '他认为短信很幼稚，很不专业。',
    '男：是的，我明白他的意思了。',
    '他认为给别人发短信非常不正式。',
    '8.那位男士说了自己什么？',
    '9.那位女士在打电话时倾向于做些什么？',
    '10.为什么这位男士第一次拿到手机时会给他的所有朋友们发短信呢？',
    '11.那位女士的父亲怎样看待发短信这个问题？',
  ],

  englishClueArr: [
    'M: So, Lyndsay, do you like to text message on your cell phone?',
    'W: Yeah, I text message a lot.',
    'M: I don’t do it so much. I prefer to make a call if I’m in a hurry.',
    'W: Yeah, I go both ways. Sometimes I don ’t really want to talk to the person. （9）<u>I just want to ask them one question, so it’s much easier for me just to text message. If I call them，I’ll have to have a long conversation.</u>',
    'M: Yeah, I can see what you mean. （8）<u>But I get off the phone pretty quickly when I call. I ’m not a big talker. </u>',
    "W: Yeah, that's true. You don’t talk a lot.",
    'M: So are you fast at writing the messages with your thumb?',
    'W: Well, when I first got a cell phone, I was so slow. I thought I would never text message. But then people kept text-messaging me, so I felt obliged to learn how to text message. So now I’m pretty fast. What about you?',
    "M: Actually I have the opposite problem. （10）<u>When I first got my cell phone, I thought it was so cool to text message all my friends who have one, </u>and I was pretty fast with my thumb then. But it seems like now I don't use it so much. I’ve got slower actually.",
    'W: Yeah, I think text messaging actually sort of has to do with your age. For example, people in high school, they text message a lot. But I asked my father if he texted messages, and guess what he said?',
    'M: What?',
    "W: He said he'd never text message. （11）<u>He thinks it’s very childish and unprofessional to text message. </u>",
    'M: Yeah, I can see what he means. It’s considered pretty informal to text message to someone.',
    'Questions:',
    '8. What does the man say about himself?',
    '9. What does the woman tend to do while she is on the phone?',
    '10.Why did the man text message all his friends when he first got his cell phone?',
    '11.What does the woman’s father think of text messaging?',
  ],

  chineseClueArr: [
    '男：林赛，你喜欢在手机上发短信吗？',
    '女：是的，我经常发短信。',
    '男：我不经常这么做。如果我赶时间，我更愿意打个电话。',
    '女：是的，我是两者都使用的。（9）<u>有时我真的不想和那个人说话。我只是想问他们一个问题，所以对我而言，给他们发个短信就简单多了。如果我给他们打电话的话，就不得不长时间的谈话。</u>',
    '男：是的，我能明白你的意思。（8）<u>但是当我打电话时，我很快就会挂电话。我不是个爱说大话的人。</u>',
    '女：是的，这倒是真的。你话不多。',
    '男：你写信息的时候拇指打字速度很快吗？',
    '女：当我第一次拿手机发信息的时候，我很慢。我以为我永远不会发短信。但是当人们不停地给我发短信时，我觉得自己有必要学习如何发短信。所以现在我很快。那你呢？',
    '男：其实我和你恰恰相反。（10）<u>当我拥有第一部手机的时候，我觉得给所有拥有手机的朋友发短信是一件超酷的事情</u>，那时我拇指打字速度很快。但现在看来，我并不怎么用它了。实际上我变慢了。',
    '女：是的，我认为短信实际上与你的年龄有关。例如，在高中的时候，人们经常发短信。但我问我父亲他是否发短信，猜猜他说什么？',
    '男：什么？',
    '女：他说他绝不会发短信。（11）<u>他认为短信很幼稚，很不专业。</u>',
    '男：是的，我明白他的意思了。他认为给别人发短信非常不正式。',
    '问题：',
    '8.那位男士说了自己什么？',
    '9.那位女士在打电话时倾向于做些什么？',
    '10.为什么这位男士第一次拿到手机时会给他的所有朋友们发短信呢？',
    '11.那位女士的父亲怎样看待发短信这个问题？',
  ],

  optionEnglish: [
    [
      'He’s got addicted to technology.',
      'He is not very good at socializing.',
      'He is crazy about text-messaging.',
      'He does not talk long on the phone.',
    ],
    ['Talk big.', 'Talk at length.', 'Gossip a lot.', 'Forget herself.'],
    ['He thought it was cool.', 'He needed the practice.', 'He wanted to stay connected with them.', 'He had an urgent message to send.'],
    ['It poses a challenge to seniors.', 'It saves both time and money.', 'It is childish and unprofessional.', 'It is cool and convenient.'],
  ],

  optionsChinese: [
    ['他对科技着迷。', '他不太擅长社交。', '他对短信很着迷。', '他在电话里没有讲很长时间。'],
    ['吹牛。', '滔滔不绝地讲话。', '经常八卦。', '忘记自己。'],
    ['他觉得很酷。', '他需要练习。', '他想和他们保持联系。', '他有紧急的消息要传达。'],
    ['这对老年人构成了挑战。', '这样既省时又省钱。', '这既幼稚又不专业。', '它既酷又方便。'],
  ],

  questionIndex: [8, 9, 10, 11],
};

export const after_submit = {
  //文章简介,材料分析
  passage_abstract: '未听先知：从选项中出现的高频词phone，message中，可以推断出本材料的主题是关于手机短信。',
  //这篇文章的重点单词
  important_words: [
    'text v. 发短信',
    'in a hurry 匆忙',
    'feel obliged to 觉得应该去',
    'thumb n. 拇指 ',
    'opposite adj. 相反的；对面的',
    'childish adj. 幼稚的；孩子气的',
    'unprofessional adj. 非专业的',
    'informal adj. 非正规的',
  ],
  //错误选项 analysis题目解析 interference干扰项分析
  options: [
    {
      your_answer: 3,
      correct_answer: 3,
      analysis:
        'D选项与音频中的“I get off the phone pretty quickly when I call. ”内容对应。D选项中的“does not talk long”为“get off the phone pretty quickly”的句义转述，“on the phone”与音频中的“when I call”对应。',
    },
    {
      your_answer: 1,
      correct_answer: 1,
      analysis:
        'B选项与音频中的“I’ll have to have a long conversation”内容对应。其中B选项中的“talk at length”为音频中“have a long conversation”的同义替换。',
    },
    {
      your_answer: 0,
      correct_answer: 0,
      analysis: 'A选项与音频中的“I thought it was so cool ”内容视听一致。',
    },
    {
      your_answer: 2,
      correct_answer: 2,
      analysis: 'C选项与音频中的“it’s very childish and unprofessional”内容视听一致。',
    },
  ],
};
